apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: module-app
  template:
    metadata:
      labels:
        app: module-app
    spec:
      containers:
      - name: module-app
        image: imax2600/mod1:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 3000
