FROM alpine:latest

RUN apk update && \
    apk add --no-cache curl

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh

WORKDIR /app

ENTRYPOINT ["/bin/bash"]