
replicaCount: 2

appName: "module1-app"

container:
  name: "module1"
  image: "imax2600/mod1:latest"
  imagePullPolicy: Always
  port: 3000

serviceName: "module1-service"
serviceType: LoadBalancer

ports:
  protocol: TCP
  port: 4000
  targetport: 3000