
replicaCount: 2

appName: "module2-app"

container:
  name: "module2"
  image: "imax2600/mod1:latest"
  imagePullPolicy: Always
  port: 3000

serviceName: "module2-service"
serviceType: Loadbalancer

ports:
  protocol: TCP
  port: 3000
  targetport: 3000