
replicaCount: 2

appName: "module3-app"

container:
  name: "module3"
  image: "imax2600/mod1:latest"
  imagePullPolicy: Always
  port: 3000

serviceName: "module3-service"
serviceType: Loadbalancer

ports:
  protocol: TCP
  port: 3000
  targetport: 3000